# -*- coding: utf-8 -*-
"""invoice_parser.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NNOQGFoihZ9Wk8ypDf5-GEBnf5MQQTvt
"""

!pip install pdfplumber

import os
import pdfplumber

# Directory containing your PDFs
pdf_folder = "/content/pdfs"
output_folder = "parsed_texts"
os.makedirs(output_folder, exist_ok=True)

# Loop through each PDF file
for filename in os.listdir(pdf_folder):
    if filename.lower().endswith(".pdf"):
        pdf_path = os.path.join(pdf_folder, filename)
        output_path = os.path.join(output_folder, f"{os.path.splitext(filename)[0]}.txt")

        print(f"Parsing {filename}...")

        with pdfplumber.open(pdf_path) as pdf:
            all_text = ""
            for i, page in enumerate(pdf.pages):
                text = page.extract_text() or ""
                all_text += f"\n--- Page {i+1} ---\n{text}\n"

        # Save or print
        with open(output_path, "w", encoding="utf-8") as f:
            f.write(all_text)
        print(f"✅ Saved parsed text to {output_path}\n")

print("All PDFs parsed.")

import os
import re
import json

# -----------------------------
# CONFIG
# -----------------------------
input_folder = "parsed_texts"
output_folder = "json_invoices"
os.makedirs(output_folder, exist_ok=True)


# -----------------------------
# HELPER FUNCTIONS
# -----------------------------
def extract_amount(value):
    """Convert strings like '$123.45' to float"""
    try:
        return float(re.sub(r"[^0-9.]", "", value))
    except:
        return None


def base_schema():
    """Consistent invoice schema for all templates, with optional fields set to None"""
    return {
        "invoice_number": None,
        "patient_id": None,
        "invoice_date": None,
        "due_date": None,
        "patient_name": None,
        "patient_age": None,
        "patient_address": None,
        "patient_phone": None,
        "patient_email": None,
        "admission_date": None,
        "discharge_date": None,
        "subtotal_amount": None,
        "discount_amount": None,
        "total_amount": None,
        "provider_name": None,
        "bed_id": None,
        "line_items": []
    }



# -----------------------------
# TEMPLATE PARSERS
# -----------------------------
def _parse_money_line_exact(text, label):
    pattern = rf"(?m)^\s*{re.escape(label)}\s*\$?([\d,]+\.\d{{2}})\s*$"
    m = re.search(pattern, text, re.IGNORECASE)
    return float(m.group(1).replace(",", "")) if m else None


def _find_last_amount_line(text):
    pattern = r"(?m)^\s*Total(?:\s*[:])?\s*\$?([\d,]+\.\d{2})\s*$"
    matches = re.findall(pattern, text, re.IGNORECASE)
    return float(matches[-1].replace(",", "")) if matches else None


def parse_hot_springs(text):
    invoice = base_schema()  # start with consistent schema

    # -----------------------------
    # Provider (doctor names)
    # -----------------------------
    provider_match = re.findall(r"Dr\.\s+[A-Z][a-zA-Z'-]+\s+[A-Z][a-zA-Z'-]+", text)
    if provider_match:
        invoice["provider_name"] = ", ".join(provider_match)
    else:
        invoice["provider_name"] = "Hot Springs General Hospital"

    # -----------------------------
    # Invoice/date/patient ID
    # -----------------------------
    inv_line = re.search(r"Invoice #\s*(\S+)\s*Date:\s*([\d-]+)\s+([\d-]+)\s+(\S+)", text)
    if inv_line:
        invoice["invoice_number"] = inv_line.group(1)
        invoice["invoice_date"] = inv_line.group(2)
        invoice["due_date"] = inv_line.group(3)
        invoice["patient_id"] = inv_line.group(4)

    # -----------------------------
    # Patient details
    # -----------------------------
    name_match = re.search(r"Patient Name:\s*(.+?)\s*Hospital No:", text)
    if name_match:
        invoice["patient_name"] = name_match.group(1).strip()

    age_match = re.search(r"Patient Age:\s*(\d+)", text)
    if age_match:
        invoice["patient_age"] = int(age_match.group(1))

    bed_match = re.search(r"Bed No:\s*(\S+)", text)
    if bed_match:
        invoice["bed_id"] = bed_match.group(1)

    # -----------------------------
    # Patient address (merge split lines)
    # -----------------------------
    addr_match = re.search(
        r"\n([0-9].+)\nAddress:\s*Admission Date:\s*[\d-]+\n([A-Za-z\s]+, [A-Z]{2,} \d{5})",
        text
    )
    if addr_match:
        invoice["patient_address"] = f"{addr_match.group(1).strip()}, {addr_match.group(2).strip()}"

    # -----------------------------
    # Admission/discharge dates
    # -----------------------------
    ad_match = re.search(r"Admission Date:\s*([\d-]+)", text)
    dc_match = re.search(r"Discharge Date:\s*([\d-]+)", text)
    if ad_match:
        invoice["admission_date"] = ad_match.group(1)
    if dc_match:
        invoice["discharge_date"] = dc_match.group(1)

    # -----------------------------
    # Financials
    # -----------------------------
    def _parse_money_line_exact(text, label):
        pattern = rf"(?m)^\s*{re.escape(label)}\s*\$?([\d,]+\.\d{{2}})\s*$"
        m = re.search(pattern, text, re.IGNORECASE)
        return float(m.group(1).replace(",", "")) if m else None

    def _find_last_amount_line(text):
        pattern = r"(?m)^\s*Total(?:\s*[:])?\s*\$?([\d,]+\.\d{2})\s*$"
        matches = re.findall(pattern, text, re.IGNORECASE)
        return float(matches[-1].replace(",", "")) if matches else None

    invoice["subtotal_amount"] = _parse_money_line_exact(text, "Sub Total") or _parse_money_line_exact(text, "Subtotal")
    invoice["discount_amount"] = _parse_money_line_exact(text, "Discount")
    invoice["total_amount"] = _find_last_amount_line(text)

    # -----------------------------
    # Line items
    # -----------------------------
    line_pattern = re.compile(r"(?m)^\s*([A-Z0-9]{2,})\s+(.+?)\s+\$([\d,]+\.\d{2})\s*$")
    items = []
    for code, desc, amt in line_pattern.findall(text):
        if desc.strip().lower() == "discount":
            continue
        items.append({
            "code": code,
            "description": desc.strip(),
            "amount": float(amt.replace(",", ""))
        })
    invoice["line_items"] = items

    return invoice

def parse_rose_petal(text):
    invoice = base_schema()  # consistent schema

    # -----------------------------
    # Provider / doctor
    # -----------------------------
    provider_match = re.search(r"(?i)Doctor[:\s]*(Dr\.\s+[A-Z][a-z]+(?:\s+[A-Z][a-z]+)?)", text)
    invoice["provider_name"] = provider_match.group(1).strip() if provider_match else None

    # -----------------------------
    # Invoice number
    # -----------------------------
    inv_match = re.search(r"Invoice\s*No[:\s]*([A-Z0-9-]+)", text)
    invoice["invoice_number"] = inv_match.group(1).strip() if inv_match else None

    # -----------------------------
    # Invoice and due dates
    # -----------------------------
    # Due date (explicit match)
    due_match = re.search(r"Due\s*Date[:\s]*(\d{4}-\d{2}-\d{2})", text, re.IGNORECASE)
    invoice["due_date"] = due_match.group(1).strip() if due_match else None

    # Invoice date (must NOT be preceded by "Due")
    date_match = re.search(r"(?<!Due\s)Date[:\s]*(\d{4}-\d{2}-\d{2})", text, re.IGNORECASE)
    invoice["invoice_date"] = date_match.group(1).strip() if date_match else None


    # -----------------------------
    # Patient name (line between clinic address and Invoice No)
    # -----------------------------
    lines = text.splitlines()
    patient_name = None
    for i, line in enumerate(lines):
        if "ROSE PETAL CLINIC" in line.upper() and i + 2 < len(lines):
            # assume next line is clinic address, then patient name
            patient_name = lines[i + 2].strip()
            break
    invoice["patient_name"] = patient_name if patient_name else None

    # -----------------------------
    # Patient contact info
    # -----------------------------
    patient_phone_match = re.search(r"\(?\d{3}\)?[-.\s]?\d{3}[-.\s]?\d{4}", text)
    invoice["patient_phone"] = patient_phone_match.group(0).strip() if patient_phone_match else None


    email_match = re.search(r"[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}", text)
    invoice["patient_email"] = email_match.group(0).strip() if email_match else None

    # -----------------------------
    # Patient address — not provided
    # -----------------------------
    invoice["patient_address"] = None
    invoice["patient_age"] = None
    invoice["bed_id"] = None
    invoice["admission_date"] = None
    invoice["discharge_date"] = None

    # -----------------------------
    # Line items
    # -----------------------------
    items_section = re.search(r"Description\s*Code\s*Total(.*?)(?:Subtotal|Sub\s*Total)", text, re.S | re.I)
    items = []
    if items_section:
        for line in items_section.group(1).splitlines():
            m = re.match(r"([A-Za-z\s]+)\s+([A-Z0-9]+)\s*\$?([\d,]+\.\d{2})", line.strip())
            if m:
                desc, code, amt = m.groups()
                items.append({
                    "description": desc.strip(),
                    "code": code.strip(),
                    "amount": float(amt.replace(",", ""))
                })
    invoice["line_items"] = items

    # -----------------------------
    # Financials
    # -----------------------------
    subtotal_match = re.search(r"(?:Sub\s?Total|Subtotal)[:\s]*\$?([\d,]+\.\d{2})", text)
    invoice["subtotal_amount"] = float(subtotal_match.group(1).replace(",", "")) if subtotal_match else None

    discount_match = re.search(r"Discount[:\s]*\$?([\d,]+\.\d{2})", text)
    invoice["discount_amount"] = float(discount_match.group(1).replace(",", "")) if discount_match else None

    total_match = re.findall(r"Total[:\s]*\$?([\d,]+\.\d{2})", text)
    invoice["total_amount"] = float(total_match[-1].replace(",", "")) if total_match else None

    return invoice

def parse_white_petal(text):
    invoice = base_schema()  # start from consistent schema

    # Invoice number
    inv_match = re.search(r"Invoice #\s*(\S+)", text)
    invoice["invoice_number"] = inv_match.group(1) if inv_match else None

    # Dates
    date_match = re.search(r"Date of Issue\s*(\d{4}-\d{2}-\d{2})", text)
    due_match = re.search(r"Due Date\s*(\d{4}-\d{2}-\d{2})", text)
    invoice["invoice_date"] = date_match.group(1) if date_match else None
    invoice["due_date"] = due_match.group(1) if due_match else None

    # Patient name
    patient_match = re.search(r"BILLED TO:\s*(.+)", text)
    invoice["patient_name"] = patient_match.group(1).strip() if patient_match else None

    # Patient address: next 2 lines after BILLED TO
    address_lines = re.findall(r"BILLED TO:.*\n(.+)\n(.+)\n", text)
    if address_lines:
        invoice["patient_address"] = " ".join([line.strip() for line in address_lines[0]])

    # Line items
    line_items = []
    items_section = re.search(r"CODE DESCRIPTION AMOUNT(.*?)(?:Subtotal|Discount|TOTAL)", text, re.S)
    if items_section:
        for line in items_section.group(1).splitlines():
            m = re.match(r"([A-Z0-9]+)\s+(.+?)\s+\$([\d,]+\.\d{2})", line.strip())
            if m:
                code, desc, amt = m.groups()
                line_items.append({
                    "code": code.strip(),
                    "description": desc.strip(),
                    "amount": float(amt.replace(",", ""))
                })
    invoice["line_items"] = line_items

    # Subtotal, discount, total
    subtotal = re.search(r"Subtotal\s*\$([\d,]+\.\d{2})", text)
    discount = re.search(r"Discount\s*\$([\d,]+\.\d{2})", text)
    total = re.search(r"TOTAL\s*\$([\d,]+\.\d{2})", text)

    invoice["subtotal_amount"] = float(subtotal.group(1).replace(",", "")) if subtotal else None
    invoice["discount_amount"] = float(discount.group(1).replace(",", "")) if discount else None
    invoice["total_amount"] = float(total.group(1).replace(",", "")) if total else None

    # Provider_name remains None
    invoice["provider_name"] = None

    return invoice



# -----------------------------
# MAIN PARSING LOOP
# -----------------------------
for filename in os.listdir(input_folder):
    if not filename.endswith(".txt"):
        continue

    path = os.path.join(input_folder, filename)
    with open(path, "r", encoding="utf-8") as f:
        text = f.read()

    if "HOT SPRINGS GENERAL" in text:
        template = "hot_springs"
        parsed = parse_hot_springs(text)
    elif "ROSE PETAL CLINIC" in text:
        template = "rose_petal"
        parsed = parse_rose_petal(text)
    elif "WHITE PETAL HOSPITAL" in text.upper():
        template = "white_petal"
        parsed = parse_white_petal(text)
    else:
        template = "unknown"
        parsed = base_schema()
        parsed["error"] = "Unknown template"

    out_path = os.path.join(output_folder, f"{os.path.splitext(filename)[0]}_{template}.json")
    with open(out_path, "w", encoding="utf-8") as f:
        json.dump(parsed, f, indent=2)

    print(f"✅ Parsed {filename} as {template} → {out_path}")

print("All invoices processed.")

