#consent formatting

import Label_invoices_NER

consent_formatting = "{patient_name:{type:string,help:Full legal name of patient},patient_first_name:{type:string|null},patient_middle_name:{type:string|null,help:Patient's middle name or initial},patient_last_name:{type:string|null,help:Patient's last name},patient_address_name:{type:string|null,help:Street address of patient, NOT HOSPITAL ADDRESS},patient_id:{type:string|null,help:Unique identifier for patient record},patient_dob:{type:string|null,format:YYYY-MM-DD},patient_signature:{type:string,help:Indicator of patient signature},patient_state:{type:string|null},patient_city:{type:string|null,help:City of patient residence},patient_zip_code:{type:string|null,help:ZIP code of patient address},provider_name:{type:string,help:Name of Doctor, NOT NAME OF HOSPITAL},provider_address_name:{type:string,help:Address of healthcare provider NOT PATIENT ADDRESS},provider_phone:{type:string|null,help:Provider phone number NOT PATIENT PHONE},provider_fax:{type:string|null},provider_state:{type:string,help:State where provider is located},provider_city:{type:string},provider_zip_code:{type:string},family_name:{type:string|null,help:Full name of family member or emergency contact},family_relation:{type:string|null,help:Relationship of family member to patient},fam_phone:{type:string|null,help:Contact phone number of family member},family_address_name:{type:string|null,help:Address of family member or contact},family_state:{type:string|null,help:State of family member residence},family_city:{type:string|null},family_zip_code:{type:string|null},guardian_name:{type:string|null,help:Name of parent or legal guardian (if patient is a minor)},guardian_signature:{type:string|null,help:Signature of guardian signing on behalf of minor},guardian_relation:{type:string|null},date:{type:string,format:YYYY-MM-DD,help:Date consent was given},expiration_date:{type:string|null,format:YYYY-MM-DD,help:Date consent expires if applicable},expiration_event:{type:string|null,help:Event after which consent expires},translator_name:{type:string|null,help:Name of translator if patient required one},translator_signature:{type:string|null,help:Indicator of translator signature}}"
system_prompt = "You are performing NER labeling on hospital consent forms. Extract the following fields in strict JSON format (no text outside JSON): " + consent_formatting +". If a field is missing, set it to null. Use Common Sense when filling fields, for example info@whitepetalhospital.org would NOT be the patient email as it is clearly a hospital email. BE SURE TO MAKE THE DISTINCTION BETWEEN HOSPITAL AND PATIENT INFO SUCH AS ADRESS, PHONE, ZIP CODE, ECT. A way to tell this is patent info is usally close to other patient info"



Label_invoices_NER.parse(system_prompt,"input_consent_forms","output_consent_forms","output_audit.txt")